openapi: 3.0.0
info:
  title: API de Ejemplo
  version: 1.0.0
  description: Esta es una API mínima de ejemplo para la documentación.
paths:
  /hello:
    get:
      summary: Devuelve un mensaje de saludo
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hola, mundo!
