openapi: 3.0.0
info:
  title: Mi API Backend
  version: 1.0.0
  description: Documentación de mis endpoints
servers:
  - url: http://localhost:8080
paths:
  /usuarios:
    get:
      summary: Lista de usuarios
      responses:
        '200':
          description: Devuelve todos los usuarios
    post:
      summary: Crear un usuario
      responses:
        '201':
          description: Usuario creado
  /auth:
    post:
      summary: Inicia sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Sesión iniciada
  /perfil:
    get:
      summary: Obtiene el perfil del usuario autenticado
      responses:
        '200':
          description: Perfil retornado
  /notificaciones:
    get:
      summary: Lista notificaciones del usuario
      responses:
        '200':
          description: Notificaciones retornadas
